import ForeignerTrackingBookComponent from "@/components/ForeignerTrackingBook";
import CheckAuth from "@/components/checkAuth.js";
import styles from "@/styles/Home.module.css";
import cn from "classnames";
import Head from 'next/head';
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import NewLayout from "../../NewLayout";

export default function ForeignerTrackingBookPage() {
  const [loading, setLoading] = useState(true)
  const router = useRouter()

  useEffect(() => {
    const token = sessionStorage.getItem('token')
    if (!token) {
      router.push('/dang-nhap')
    } else {
      setLoading(false)
    }
  }, [])

  return (
    <>
      <Head>
        <title>Sổ đăng ký người nước ngoài</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon-logo.png" />
      </Head>
      <main className={cn(styles.main)}>
        {loading && <CheckAuth />}
        <NewLayout>
          <ForeignerTrackingBookComponent />
        </NewLayout>
      </main>
    </>
  );
}

