const TextTheDay = {
	trackProcessingOfTheDay: {
		stt: 'STT',
		licensePlates: 'Biển kiểm soát',
		dateOfViolation: 'Ngày vi phạm',
		addressOfViolation: 'Địa điểm vi phạm',
		violation: 'Lỗi vi phạm',
		fullName: 'Tên người vi phạm',
		custody: 'Tạm giữ',
		handoverUnit: 'Đơn vị bàn giao',
		receiver: 'Cán bộ tiếp nhận',
		amount: 'Tiền cược',
		picture: 'Hình ảnh đính kèm',
		result: 'Kết quả xử lý',
	},
	defaultOption: 'Chọn giá trị',
	plus: '+',
	infoUser: {
		name: 'Michale Phạm',
	},
	inputRequired: '(*) là những trường bắt buộc phải nhập.',
	error: {
		border: '1px solid var(--validate-error)',
	},
	statusTrue: 200,
	keyEnter: 13,
	router: {
		login: '/dang-nhap',
	},
	title: {
		trackProcessingOfTheDay: 'Sổ theo dõi xử lý trong ngày',
	},
	search: {
		searchPlaceholder: 'Tìm kiếm...',
	},
	CRUD: {
		add: 'Thêm',
		cancel: 'Hủy',
		insert: 'Sửa',
		delete: 'Xoá',
		close: 'Đóng',
		end: 'Xong',
		deleteConfirm: 'Bạn có chắc muốn xóa thông tin này ?',
		backgroundDeleteModal: 'rgba(3, 3, 3, 0.1)',
		dateStart: 'Ngày Bắt Đầu:',
		dateEnd: 'Ngày Kết Thúc:',
	},
	fiveImageFiles: 5,
	twoMillionBytes: 2000000,
	twoMegaByte: '2Mb',
	imageTypes: ['image/png', 'image/jpg', 'image/jpeg'],
	imageTypesString: '.png, .jpg, jpeg',
	uploadFromModal: true,
	exportFile: 'Xuất file',
	colon: ':',
	notify: {
		notifySuccess: 'Đã tải xuống file',
		notifyError: 'Có lỗi xảy ra,vui lòng thử lại',
	},
};
export default TextTheDay;
