import Head from 'next/head'
import { Inter } from '@next/font/google'
import Header from '@/layouts/header'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import CheckAuth from '@/components/checkAuth.js'
import CustodyFolowBook from '@/components/custodyFolowBook'
import NewLayout from '@/NewLayout'
const inter = Inter({ subsets: ['latin'] })

export default function PersonalBookPage() {
    const [loading, setLoading] = useState(true)
    const router = useRouter()

    useEffect(() => {
        const token = localStorage.getItem('token')
        if (!token) {
            router.push('/dang-nhap')
        } else {
            setLoading(false)
        }
    }, [])


    return (
        <>
            <Head>
                <title>Sổ theo dõi tạm giữ, giấy tờ và vi phạm giao thông</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon-logo.png" />
            </Head>
            <main>
                {loading && <CheckAuth />}
                <Header />
                <NewLayout>
                    <CustodyFolowBook />
                </NewLayout>
            </main>
        </>
    )
}