import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import cn from 'classnames'
import DispatchBook from '@/NewComponents/DispatchBook/dispatchBook'
import Header from '@/layouts/header'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import CheckAuth from '@/components/checkAuth.js'
import NewLayout from '../../NewLayout'


const inter = Inter({ subsets: ['latin'] })

export default function DispatchBookPage() {
  const [loading,setLoading] = useState(true)
  const router = useRouter()

  useEffect(()=>{
    const token = localStorage.getItem('token')
    if(!token) {
     router.push('/dang-nhap')
    } else {
      setLoading(false)
    }
   },[])
  return (
    <>
      <Head>
        <title>Sổ tiếp nhận công văn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon-logo.png" />
      </Head>
      <main style={{ marginTop: "52px" }}>
        {loading && <CheckAuth/>}
        <NewLayout><DispatchBook/></NewLayout>
      </main>
    </>
  )
}
