const Text = {
	administrative: {
		stt: 'STT',
		textReceiptDate: 'Ngày tháng năm nhận VB',
		textNumber: 'Số văn bản',
		issuedDate: 'Ngày ban hành ',
		agencyIssued: 'Cơ quan ban hành',
		handlingOfficer: 'Cán bộ giải quyết',
		timeLimitForSolving: 'Thời hạn giải quyết',
		resultEvaluation: 'Đánh giá kết quả (Hoàn thành/Chưa hoàn thành)',
	},
	titledispatch: {
		stt: 'STT',
		dateTime: 'Ngày tháng năm',
		dispatchID: 'Số công văn',
		releaseDate: 'Ngày tháng ban hành',
		subject: 'Trích yếu',
		agencyIssued: 'Cơ quan ban hành',
		receiver: 'Người nhận',
	},
	caseHandlingLogBook: {
		stt: 'STT',
		dateMayHappened: 'Ngày tháng năm xảy ra',
		nameOfTheCase: 'Tên vụ việc',
		thePlaceWhereItHappened: ' Địa điểm xảy ra',
		content: 'Nội dung',
		acceptanceOfficer: 'Cán bộ thụ lý',
		processingResults: 'Kết quả xử lý',
		violatingImages: 'Hình ảnh vi phạm',
	},
	titleForeignerTrackingBook: {
		stt: 'STT',
		registerDate: 'Ngày đăng ký',
		fullName: 'Họ và tên',
		birthDay: 'Ngày tháng năm sinh',
		country: 'Quốc tịch',
		residentialAddress: 'Địa chỉ cư trú',
		passport: 'Số hộ chiếu',
		recidencePermitNumber: 'Số giấy tờ cho cư trú',
		job: 'Nghề nghiệp',
		entryDate: 'Ngày nhập cảnh',
		gateEntry: 'Cửa khẩu nhập cảnh',
		entryPurpose: 'Mục đích nhập cảnh',
		sojournDateFrom: 'Ngày bắt đầu tạm trú',
		sojournDateTo: 'Ngày đi',
		guarantorName: 'Họ và tên chủ nhà',
		fullNamePolice: 'Cán bộ đăng ký',
		PoliceLead: 'Chỉ huy ký',
	},
	titlelogbook: {
		stt: 'STT',
		decisionId: 'Số quyết định',
		fullName: 'Họ và tên',
		birthday: 'Ngày tháng năm sinh',
		staying: 'Hộ khẩu thường trú, tạm trú \n(Ghi rõ xã, phường)',
		nation: 'Dân tộc',
		country: 'Quốc tịch',
		job: 'Nghề nghiệp, nơi làm việc',
		content: 'Nội dung vi phạm \n(Ghi rõ thời gian, ngày, tháng, năm, lỗi vi phạm)',
		punisher: 'Người ra quyết định xử phạt \n(Ghi rõ thời gian, ngày, tháng, năm)',
		processingForm: 'Hình thức xử lý \n(Ghi rõ số tiền xử phạt)',
		fullnamePolice: 'Cán bộ được phân công xử lý',
	},
	titlepersonal: {
		stt: 'STT',
		date: 'Ngày tháng năm',
		fullName: 'Họ tên người xin xác nhận',
		birthday: 'Ngày tháng năm sinh',
		staying: 'Hộ khẩu thường trú',
		grantReason: 'Lý do xác nhận',
		verifier: 'Cán bộ xác nhận',
		leaderSign: 'Chỉ huy ký',
		payBackDay: 'Ngày trả',
		errorDay: 'Ngày vi phạm',
		errorPersonName: 'Tên người vi phạm',
		custody: 'Đã tạm giữ',
		payBack: 'Đã trả lại',
		cadres: 'Cán bộ trả',
		// Duty Book Start
		dutyBook: {
			hourDuty: 'Giờ trực',
			shift: 'Ca trực:',
			duty: 'Trực lãnh đạo, chỉ huy. Trực ban',
			totalOfPeople: 'Quân số thường trực chiến đấu',
			total: 'Tổng số',
			present: 'Có mặt',
			absent: 'Vắng',
			reason: 'Có lý do',
			notReason: 'Không có lý do',
			excusedAbsence: 'Vắng có lý do',
			absenceNoReason: 'Vắng không có lý do',
			contentOfShift: `Nội dung ca trực (Tiếp nhận đầy đủ tình hình, tài liệu, hồ sơ, phương tiện, thiết
                  bị, tài sản của ca trực trước bàn giao và thu nhận thông tin, tài liệu, vụ việc,...
                  có trong ca trực)`,
			informationOfShift: 'Xử lý thông tin, tài liệu, vụ việc của lãnh đạo, chỉ huy',
			directiveInformation: 'Chỉ đạo xử lý thông tin, tài liệu, vụ việc của lãnh đạo, chỉ huy',
			fullNameReceiver: 'Cán bộ bàn giao (Ký, ghi rõ họ tên)',
			fullNameHandover: 'Cán bộ nhận (Ký, ghi rõ họ tên)',
			leadShift: 'Chỉ huy ca trực (Ký, ghi rõ họ tên)',
			placeHolder: {
				contentOfShift: 'Nội dung ca trực',
			},
		},
		//Duty Book End
		//statusBookOfTheDay
		standingForce: 'Lực Lượng Trực',
		caseName: 'Tên Vụ Việc, Tình Hình',
		location: 'Địa Điểm Xảy Ra',
		Content: 'Nội Dung',
		handling: 'Cán Bộ Xử Lý',
		custody: 'Tạm Giữ',
		return: 'Trao Trả',
		handOver: 'Bàn Giao Ca Sau',

		// end statusBookOfTheDay
		// Foreigner Tracking Book
		foreignerTrackingBook: {
			stt: 'STT',
			fullName: 'Họ và tên',
			birthDay: 'Ngày tháng năm sinh',
			gender: 'Giới tính',
			country: 'Quốc tịch',
			passport: 'Sổ hộ chiếu',
			entryDate: 'Ngày nhập cảnh',
			visaDuration: 'Thời hạn thị thực',
			visaDateFrom: 'Từ ngày',
			visaDateTo: 'Đến ngày',
			sojournDuration: 'Thời hạn tạm trú',
			sojournDateFrom: 'Từ ngày',
			sojournDateTo: 'Đến ngày',
			guarantor: 'Cơ quan, tổ chức, cá nhân bảo lãnh',
			guarantorName: 'Tên',
			guarantorAddress: 'Địa chỉ',
			guarantorRelationship: 'Quan hệ với người bảo lãnh',
			note: 'Ghi chú',
			roomNumber: 'Số phòng (Nếu có)',
			male: 'Nam',
			female: 'Nữ',
			placeHolder: {
				visaDurationFrom: 'Thời hạn thị thực từ',
				visaDurationTo: 'Thời hạn thị thực đến',
				sojournDurationFrom: 'Thời hạn tạm trú từ',
				sojournDurationTo: 'Thời hạn tạm trú đến',
				guarantorAddress: 'Địa chỉ cơ quan, tổ chức, cá nhân bảo lãnh',
			},
		},
		// Foreigner Tracking Book End

		//nothandle
	},
	nothandle: {
		stt: 'STT',
		violation: 'Biển kiểm soát',
		dateOfViolation: 'Ngày tháng năm vi phạm',
		LocationOfViolation: 'Địa điểm vi phạm',
		errorViolation: 'Lỗi vi phạm',
		violatorName: 'Tên người vi phạm',
		applicantName: 'Tên người xin',
		commandSettlement: 'Chỉ huy giải quyết',
		OfficersReceiveStickers: 'Cán bộ nhận giấy dán',
	},
	dutyBook: {
		hourDuty: 'Giờ trực',
		duty: 'Trực lãnh đạo, chỉ huy. Trực ban',
		totalOfPeople: 'Quân số thường trực chiến đấu',
		total: 'Tổng số',
		present: 'Có mặt',
		absent: 'Vắng',
		reason: 'Có lý do',
		notReason: 'Không có lý do',
		excusedAbsence: 'Vắng có lý do',
		absenceNoReason: 'Vắng không có lý do',
		contentOfShift: `Nội dung ca trực (Tiếp nhận đầy đủ tình hình, tài liệu, hồ sơ, phương tiện, thiết
              bị, tài sản của ca trực trước bàn giao và thu nhận thông tin, tài liệu, vụ việc,...
              có trong ca trực)`,
		informationOfShift: 'Xử lý thông tin, tài liệu, vụ việc của lãnh đạo, chỉ huy',
		directiveInformation: 'Chỉ đạo xử lý thông tin, tài liệu, vụ việc của lãnh đạo, chỉ huy',
		fullNameReceiver: 'Cán bộ bàn giao (Ký, ghi rõ họ tên)',
		fullNameHandover: 'Cán bộ nhận (Ký, ghi rõ họ tên)',
		leadShift: 'Chỉ huy ca trực (Ký, ghi rõ họ tên)',
		placeHolder: {
			contentOfShift: 'Nội dung ca trực',
		},
	},
	trafficbook: {
		stt: 'STT',
		days: 'Thứ',
		date: 'Ngày Tháng Năm',
		trafficIntersection: 'Nút Giao Thông',
		morning: "Buổi Sáng \n 06h30' - 07h45'",
		afternoon: "Buổi Chiều \n 17h00' - 18h15'",
		note: 'Ghi Chú',
	},
	titleCell: {
		stt: 'STT',
		sentDay: 'Ngày chuyển kiểm định',
		licensePlates: 'Biển kiểm soát',
		receiver: 'Người nhận',
		violation: 'Lỗi vi phạm',
		fullName: 'Họ và tên',
		dateOfBirth: 'Ngày tháng năm sinh',
		sex: 'Giới tính',
		permanentResidence: 'Hộ khẩu thường trú',
		confirmedDate: 'Ngày tháng xác nhận',
		inspectionOfficer: 'Cán bộ kiểm tra',
		leaderSign: 'Lãnh đạo ký',
		payBackDay: 'Ngày trả',
		dateOfViolation: 'Ngày vi phạm',
		errorPersonName: 'Tên người vi phạm',
		custody: 'Đã tạm giữ',
		payBack: 'Đã trả lại',
		cadres: 'Cán bộ trả',
		location: "Địa điểm vi phạm",
		officersStickFines: "Cán bộ dán phạt",
		handlingOfficer: "Cán bộ xử lý",
		hinePaymentDate: "Ngày nộp phạt"
	},
	passport: {
		stt: 'STT',
		fullName: 'Họ Và Tên',
		birthday: 'Ngày Tháng Năm Sinh',
		gender: 'Giới Tính',
		staying: 'Hộ Khẩu Thường Trú (Tạm Trú)',
		confirmationDate: 'Ngày Tháng Xác Nhận',
		fullNamePolice: 'Cán Bộ Kiểm Tra',
		leaderSign: 'Lãnh Đạo Ký',
	},
	eventBook: {
		date: 'Ngày tháng',
		location: 'Địa điểm',
		force: 'Lực lượng',
		mission: 'Nhiệm vụ',
		note: 'Ghi chú',
	},
	residentbook: {
		stt: 'STT',
		date: 'Ngày tháng năm kiểm tra',
		address: 'Địa chỉ kiểm tra',
		host: 'Chủ nhà trọ/ chủ hộ',
		fullName: 'Họ tên người được kiểm tra',
		citizenNumber: 'Số CCCD',
		violationer: 'Người vi phạm',
		formProcessing: 'Hình thức xử lý',
		policeCheck: 'CSKV kiểm tra',
	},
	impoundbook: {
		stt: 'STT',
		returnDate: 'Ngày trả',
		licensePlates: 'Biển kiểm soát',
		dateOfViolation: 'Ngày vi phạm',
		fullname: 'Tên người vi phạm',
		onHold: 'Đã tạm giữ',
		returned: 'Đã trả lại',
		officerReturns: 'Cán bộ trả',
	},
	dataWeeklyAssignment: {
		stt: 'STT',
		day: 'Thứ',
		date: 'Ngày tháng năm',
		captain: 'Trực chỉ huy',
		inHour: 'Trong giờ',
		overTime: 'Ngoài giờ',
		onDuty: 'Trực chiến',
		patrolShiftOne: 'Ca 1',
		patrolShiftTwo: ' Ca 2',
		patrol: 'Tuần tra',
		onDutyy: 'Trực ban',
	},
	followTheText: {
		stt: 'STT',
		time: 'Ngày tháng năm',
		dispatchNumber: 'Số công văn',
		releaseDate: 'Ngày tháng ban hành',
		abstract: 'Trích yếu',
		signer: ' Người ký',
		recipients: 'Nơi nhận',
	},
	statusBookOfTheDay: {
		STT: "STT",
		date: 'Ngày tháng năm',
		forceOnDuty: 'Lực lượng trực',
		caseName: 'Tên vụ việc, tình hình',
		location: 'Địa điểm xảy ra',
		content: 'Nội dung',
		receive: 'Cán bộ nhận xử lý',
		custody: 'Tạm giữ',
		returns: 'Trao trả',
		handOver: 'Bàn giao ca sau',
	},
	statusBook: {
		stt: 'STT',
		dateTime: 'Ngày Tháng',
		personOnDuty: 'Người Trực',
		details: 'Nội Dung Tình Hình',
		handler: 'Người Xử Lý',
		note: 'Ghi Chú',
	},

	// end statusbook
	//passport
	fullName: 'Họ Và Tên',
	birthday: 'Ngày Tháng Năm Sinh',
	gender: 'Giới Tính',
	staying: 'Hộ Khẩu Thường Trú (Tạm Trú)',
	confirmationDate: 'Ngày Tháng Xác Nhận',
	fullNamePolice: 'Cán Bộ Kiểm Tra',
	leaderSign: 'Lãnh Đạo Ký',

	// end passport
	//statusBookOfTheDay

	// end statusBookOfTheDay

	// passport
	fullName: 'Họ Và Tên',
	birthday: 'Ngày Tháng Năm Sinh',
	gender: 'Giới Tính',
	staying: 'Hộ Khẩu Thường Trú (Tạm Trú)',
	confirmationDate: 'Ngày Tháng Xác Nhận',
	fullNamePolice: 'Cán Bộ Kiểm Tra',
	leaderSign: 'Lãnh Đạo Ký',
	// end passport
	// Follow The Text Start
	followTheText: {
		stt: 'STT',
		time: 'Ngày tháng năm',
		dispatchNumber: 'Số công văn',
		releaseDate: 'Ngày tháng ban hành',
		abstract: 'Trích yếu',
		signer: ' Người ký',
		recipients: 'Nơi nhận',
	},
	// Follow The Text End

	// Event Book Start
	eventBook: {
		date: 'Ngày tháng',
		location: 'Địa điểm',
		force: 'Lực lượng',
		mission: 'Nhiệm vụ',
		note: 'Ghi chú',
	},
	// Event Book End

	// Inspection Deposit Book Start
	inspectionDepositBook: {
		stt: 'STT',
		licensePlates: 'Biển kiểm soát',
		dateOfViolation: 'Ngày vi phạm ',
		violation: 'Lỗi vi phạm',
		location: 'Địa điểm vi phạm',
		officersStickFines: 'Cán bộ dán phạt',
		sentDate: 'Ngày chuyển kiểm định',
		handlingOfficer: "Cán bộ xử lý",
		dateOfPaymentFfFines: 'Ngày nộp phạt',
		violatingImages: 'Hình ảnh vi phạm',
	},
	// Inspection Deposit Book End

	// CaseHandlingLogBook Start
	caseHandlingLogBook: {
		stt: 'STT',
		dateMayHappened: 'Ngày tháng năm xảy ra',
		nameOfTheCase: 'Tên vụ việc',
		thePlaceWhereItHappened: ' Địa điểm xảy ra',
		content: 'Nội dung',
		acceptanceOfficer: 'Cán bộ thụ lý',
		processingResults: 'Kết quả xử lý',
		violatingImages: 'Hình ảnh đối tượng vi phạm',
	},
	// CaseHandlingLogBook End
	pagination: {
		previous: '< Trước',
		after: 'Sau >',
	},
	CRUD: {
		add: 'Thêm',
		cancel: 'Hủy',
		insert: 'Sửa',
		delete: 'Xoá',
		close: 'Đóng',
		end: 'Xong',
		deleteConfirm: 'Bạn có chắc muốn xóa thông tin này ?',
		backgroundDeleteModal: 'rgba(3, 3, 3, 0.1)',
		dateStart: 'Ngày Bắt Đầu:',
		dateEnd: 'Ngày Kết Thúc:',
		Success: 'Đã tải xuống file',
		Error: 'Có Lỗi xảy ra, vui lòng thử lại',
	},
	plus: '+',
	placeHolder: {
		dataTracker: {
			licensePlates: '43B1-0608',
			receiver: 'Nguyễn Văn A',
			violation: 'Vượt đèn đỏ',
			date: '20-02-2002',
		},
		dataRegister: {
			fullName: 'Tên đầy đủ',
			userName: 'Tên đăng nhập',
			password: 'Mật khẩu',
			confirmPassword: 'Xác nhận mật khẩu',
		},
		dataStatus: {
			dateTime: '',
			personOnDuty: 'Nguyễn Văn A',
			details: 'Vượt đèn đỏ',
			handler: 'Nguyễn Văn A',
		},
		dataWeeklyAssignment: {
			day: 'Thứ ',
			date: '20-02-2002',
			captain: 'Nguyễn Văn A',
			inHour: 'Trực ban trong giờ',
			overTime: 'Trực ban ngoài giờ',
			onDuty: 'Trực chiến ',
			patrolShiftOne: 'Tuần tra ca 1',
			patrolShiftTwo: 'Tuần tra ca 2',
			patrol: 'Tuần tra',
		},
		dataPassport: {
			birthday: '20-02-2002',
			confirmationDate: '20-02-2002',

			fullName: 'Nguyễn Văn A',
			gender: 'Nam/Nữ',
			staying: '101 Huỳnh Tấn Phát, quận Hải Châu, Đà Nẵng',
			fullNamePolice: 'Nguyễn Văn A ',
			leaderSign: 'Nguyễn Văn A',
		},
		dataNothandle: {
			seaOfControl: '43B1-0608',
			dateOfViolation: '20-02-2002',
			LocationOfViolation: '101 Huỳnh Tấn Phát, quận Hải Châu, Đà Nẵng ',
			errorViolation: 'Lỗi Vi Phạm',
			violatorName: 'Nguyễn Văn A',
			applicantName: 'Nguyễn Văn A',
			commandSettlement: 'Nguyễn Văn A',
			OfficersReceiveStickers: 'Nguyễn Văn A',
		},
		dataPassport: {
			fullName: 'Phạm Đức Minh',
			sex: 'Nam/Nữ',
			permanentResidence: '101 Huỳnh Tấn Phát, quận Hải Châu, Đà Nẵng',
			inspectionOfficer: 'Nguyễn Thị Hà',
			leaderSign: 'Mẫn Mẫn',
		},
		traffic: {
			days: 'Nhập thứ...',
			date: 'Nhập ngày...',
			trafficIntersection: 'Tiểu La - Núi Thành',
			morning: 'Nguyễn Thế Huy',
			afternoon: 'Nguyễn Văn Thành',
			note: 'Ghi Chú',
		},
		resident: {
			date: '20-02-2002',
			address: '101 Huỳnh Tấn Phát, quận Hải Châu, Đà Nẵng',
			host: 'Phạm Đức Minh',
			fullName: 'Nguyễn Thế Huy',
			citizenNumber: '052099000000',
			violationer: 'Nguyễn Văn Hoàng Sơn',
			formProcessing: 'Không khai báo cư trú',
			policeCheck: 'Nguyễn Thế Huy',
		},
		impound: {
			returnDate: '06-03-2023',
			licensePlates: '43C1-1111',
			dateOfViolation: '01-01-2023',
			fullname: 'Phạm Vương Hùng',
			onHold: 'Thanh Khê',
			returned: 'Chưa',
			officerReturns: 'Phạm Anh',
			search: 'Tìm kiếm...',
			register: 'Đăng Ký',
			login: 'Đăng Nhập',
			choose: {
				role: 'Chọn vai trò',
			},
			dataDispatch: {
				date: '20-02-2002',
				receiver: 'Nguyễn Văn A',
				dispatchID: 'Số Công Văn',
				agencyIssued: 'Thành Phố Đà Nẵng',
				subject: 'Trích Yếu ',
				releaseDate: '20-02-2002',
			},
			dataPersonal: {
				date: '20-02-2002',
				fullName: 'Nguyễn Văn A',
				gender: 'Nam/Nữ',
				birthday: 'birthday',
				staying: '101 Huỳnh Tấn Phát, Hòa Cường Bắc, Hải Châu, Đà Nẵng',
				grantReason: 'Đi Làm',
				verifier: 'CSKV Xác Nhận',
				leaderSign: 'Lãnh Đạo Ký',
			},
			dataLog: {
				decisionId: 'Số Quyết Định',
				fullName: 'Nguyễn Văn A',
				birthday: '20-02-2002',
				staying: '101 Huỳnh Tấn Phát, Hòa Cường Bắc, Hải Châu, Đà Nẵng',
				nation: 'Kinh',
				country: 'Việt Nam',
				job: 'Nghề Nghiệp, Nơi Làm Việc',
				content: 'Vượt đèn đỏ (Ghi rõ thời gian, ngày, tháng, năm, lỗi vi phạm)',
				punisher: 'Nguyễn Văn A ( Ghi rõ thời gian, ngày, tháng, năm)',
				processingForm: 'Phạt Hành Chính (Ghi rõ số tiền xử phạt)',
				fullnamePolice: 'Nguyễn Văn A',
			},
		},
	},
	search: 'Tìm kiếm...',
	register: 'Đăng Ký',
	login: 'Đăng Nhập',
	choose: {
		role: '--Chọn vai trò--',
	},
	noRole: 0,
	noDataInTable: 'Bảng này chưa có dữ liệu.',
	gender: {
		string: {
			man: 'Nam',
			woman: 'Nữ',
		},
		number: {
			man: 0,
			woman: 1,
		},
	},
	infoUser: {
		name: 'Michale Phạm',
	},
	inputRequired: '(*) là những trường bắt buộc phải nhập.',
	error: {
		border: '1px solid var(--validate-error)',
		borderRadius: '0.85rem',
		login: '1px solid rgba(255, 177, 177, 1)',
	},
	statusTrue: 200,
	keyEnter: 13,
	router: {
		login: '/dang-nhap',
	},
	chooseValue: 'Chọn giá trị',
	exportFile: 'Xuất file',
	dateStart: 'Ngày Bắt Đầu',
	dateEnd: 'Ngày Kết Thúc',
	colon: ':',
	image: 'Hình ảnh vi phạm',
	images: 'ảnh',
	uploadImages: 'Tải ảnh lên',
	seeImages: 'Xem ảnh',
	maxQuantityImagesToShow: 2,
	dots: '.',
	fiveImageFiles: 5,
	twoMillionBytes: 2000000,
	twoMegaByte: '2Mb',
	imageTypes: ['image/png', 'image/jpg', 'image/jpeg'],
	imageTypesString: '.png, .jpg, jpeg',
	uploadFromModal: true,
	key: {
		escape: 27,
		arrowLeft: 37,
		arrowRight: 39,
	},
	disableArrowRight: 'disableArrowRight',
	disableArrowLeft: 'disableArrowLeft',
	keydown: 'keydown',
	mousedown: 'mousedown',
};

export default Text;
