import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import cn from "classnames";
import { useEffect, useState } from "react";
import Header from "@/layouts/header";
import { useRouter } from "next/router";
import Dashboard from "@/components/Dashboard";
import CheckAuth from "@/components/checkAuth.js";
import NewLayout from "../../NewLayout";

import { Text } from "../../constant";
import TableComponent from "@/components/DutyBook/tableComponent";
const inter = Inter({ subsets: ["latin"] });

export default function DutyBook() {
  const [loading, setLoading] = useState(true);
  const router = useRouter();

  useEffect(() => {
    const token = localStorage.getItem("token");
    if (!token) {
      router.push(Text.router.login);
    } else {
      setLoading(false);
    }
  }, []);

  return (
    <>
      <Head>
        <title>{"Sổ trực ban"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon-logo.png" />
      </Head>
      <main className={cn(styles.main)}>
        {loading && <CheckAuth />}
        <NewLayout>
          <TableComponent />
        </NewLayout>
      </main>
    </>
  );
}
