import Head from 'next/head'
import { Inter } from '@next/font/google'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import cn from 'classnames'
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    const router = useRouter();
    const handleValidate = () => {
      const token = localStorage.getItem('token')
      if(!token) {
       router.push('/dang-nhap')
      } else {
       router.push('/home')
      }
    }
    useEffect(()=>{
      handleValidate()
    },[])

  return (
    <>
      <Head>
        <title>CAP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/la-co-viet-nam-vector-1.png" />
      </Head>
      <main className={cn(styles.wrapper)}>
          <div className={cn(styles.ldsEllipsis)}>
                <div></div>
                <div></div>
                <div></div>
            </div>
      </main>
    </>
  ) 
}
