import Head from "next/head";
import styles from "@/styles/Home.module.css";
import cn from "classnames";
import Login from "@/components/login";
import { useEffect } from "react";
import { useDispatch } from "react-redux";
import { toggleBody } from "@/store/paddingSlice";
export default function LoginPage() {
    const dispatch = useDispatch();
    useEffect(() => {
        dispatch(toggleBody(252));
        localStorage.removeItem("token");
        localStorage.removeItem("username");
        localStorage.removeItem("roleId");
        localStorage.removeItem("fullname");
        sessionStorage.removeItem("token");
        sessionStorage.removeItem("username");
        sessionStorage.removeItem("roleId");
        sessionStorage.removeItem("fullname");
    }, []);

    return (
        <>
            <Head>
                <title>Đăng nhập</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon-logo.png" />
            </Head>
            <main className={cn(styles.main)}>
                <Login />
            </main>
        </>
    );
}
